#!/usr/local/bin/zsh

function prompt_z_help()
{
}

function prompt_z_preview ()
{
}

function prompt_z_setup()
{
    local no_color="%b%f"
    local error_color="%B%F{red}"
    local error_str="X"
    local bracket_color="%B%F{magenta}"
    local user_color="%B%F{white}"
    local at_color="%B%F{yellow}"
    local host_color="%B%F{cyan}"
    local dir_color="%B%F{blue}"
    local dollar_color="%B%F{red}"
    local git_info='$(git_prompt_info)'

    PROMPT="%(?..${error_color}${error_str}$no_color)${bracket_color}[${user_color}%n${at_color}@${host_color}%m ${dir_color}%~${no_color}${git_info}${no_color}${bracket_color}]${dollar_color}$ ${no_color}"
}

ZSH_THEME_GIT_PROMPT_PREFIX='  ('
ZSH_THEME_GIT_PROMPT_SUFFIX=')'
ZSH_THEME_GIT_PROMPT_DIRTY='%B%F{red}'
ZSH_THEME_GIT_PROMPT_CLEAN='%B%F{green}'

prompt_z_setup
